### ISSUE TITLE
Best Bets exception on add and delete

### ISSUE THREAD

**Issue by KolbeinFoldoy** [Epinova/Epinova.Elasticsearch#135]
I'm getting _[Epinova_ElasticSearch_Core_Models_IndexItem][2427]: document missing_ when adding a new best bet.
When I'm deleting I'm getting _Validation Failed: 1: type is missing;_. 

Both adding and deleting work, but I'm still getting the exception whenever I add/delete. Afterwards, I need to get update the Best Bets page to see the result of my action. 

When adding, the following form data is sent with values:
* LanguageId
* Index
* TypeName
* phrase
* contentId

However, when I delete, the value of typeName is missing. Index, languageId, phase and contentId have values.

**Comment by otanum** [comment]
Should be fixed in 11.7.4
