### ISSUE TITLE
Mapping conflict with existing mapper

### ISSUE THREAD

**Issue by KolbeinFoldoy** [Epinova/Epinova.Elasticsearch#142]
Epinova Elasticsearch version: 11.7.3.147
Episerver version: 11.20.2
ElasticSearch version: 7.11.1

I'm getting an error when using the button "Create or update indices with mapping". 

![NavinettIndexCreation](https://user-images.githubusercontent.com/69247498/141966178-49a72db3-e5e6-4446-839f-ed4dc0853880.png)

If I push the button without having an index, I receive this error:
![ErrorWhenCreatingWithMappingButton_LI](https://user-images.githubusercontent.com/69247498/141966230-f099b129-a21f-486a-bb0c-ac5d029d6fd3.jpg)
However, an index is created afterwards.

If i push the button after having created an index, I receive this error:
![ErrorWhenUpdatingWithMappingButtonWithExistingIndex_LI](https://user-images.githubusercontent.com/69247498/141966252-57596358-8649-42a7-80b2-773addf42033.jpg)

Using the blue button (Create or update index) will successfully create an index, but without updating the mapping. I recently added [Stem] on a string propperty which isn't updated in the mapping due to this error.

**Comment by otanum** [comment]
Try to drop and recreate the indices. Not possible to change analyzer of existing parameter (https://discuss.elastic.co/t/change-analyzer-of-specific-property/99012).

You could also take a look at the mapping validator. It will probably tell you the same as the exception.

**Comment by KolbeinFoldoy** [comment]
The problem is that I get this error every time I delete and create a new index with the green button.

**Comment by otanum** [comment]
Have you tried to use the mapping validator? Properties with same name must have same settings. For example if you have added stemming to one Description property and not all Description properties.
