### ISSUE TITLE
RequestTimeoutError on updating index via Episerver page tree

### ISSUE THREAD

**Issue by KolbeinFoldoy** [Epinova/Epinova.Elasticsearch#143]
Epinova Elasticsearch version: 11.7.3.147
Episerver version: 11.20.2
ElasticSearch version: 7.11.1

When using the Episerver page tree to manually update the search index, it recursively indexes all the children pages.
![image](https://user-images.githubusercontent.com/69247498/141978659-7dfc599c-5297-423f-be04-0b7cf833d264.png)

However, if the indexing takes longer than 10 seconds, it returns and RequestTimeoutError for not having received a response.
![RequestTimeoutError](https://user-images.githubusercontent.com/69247498/141978948-8713c186-f83b-460e-a62d-058aa05262e7.png)

The indexing job seems to finish indexing all the children despite receiving the RequestTimeoutError.

The request being sent upon manuelly starting indexing:
![image](https://user-images.githubusercontent.com/69247498/141979403-0f857eae-e4aa-4ad0-9a80-921a0c8024c0.png)

With the request payload:
![image](https://user-images.githubusercontent.com/69247498/141979190-6b1bf4b3-fcab-44d1-aba5-e206f2f5fa4c.png)

**Comment by otanum** [comment]
Fixed in 11.7.4.240
