### ISSUE TITLE
Querying custom type in secondary index fails due to DidYouMean being enabled

### ISSUE THREAD

**Issue by jonatanjii** [Epinova/Epinova.Elasticsearch#144]
DidYouMean is enabled by default, and there seems to be no way to disable it, when using GetCustomResults().
This causes "no mapping found for field [DidYouMean]" error when querying custom types in a secondary index.

In the async version GetCustomResultsAsync() DidYouMean is disabled:
query.EnableDidYouMean = false;

All queries using GetCustomResults() fails but the same queries using the async version works.

**Comment by otanum** [comment]
Any chance @jonatanjii  could verify 11.7.4.234-pre?

**Comment by jonatanjii** [comment]
Can´t test it but it looks ok. The only change that was required was to disable DidYouMean by default in GetCustomResults() which was already the case in the async version of the same method.
