### ISSUE TITLE
Best bets administration tab crashes if phrase contains quots

### ISSUE THREAD

**Issue by scrog** [Epinova/Epinova.Elasticsearch#146]
A user added a phrase containing quotes and now the best bet page wont load.
In the console we get an error: 
Uncaught SyntaxError: Unexpected identifier   ElasticBestBets:696  
If I look at row 696 in ElasticBestBets its the phrase with quotes.

Any idea how I can solve this?

**Comment by otanum** [comment]
Fixed in 11.7.4.229
