### ISSUE TITLE
Optimizely/Episerver CMS 12 

### ISSUE THREAD

**Issue by sinaapi** [Epinova/Epinova.Elasticsearch#149]
Hi !

Will this project support Episerver CMS  12?

**Comment by ninaulstein** [comment]
Hi, is this still the status?

**Comment by karolberezicki** [comment]
Hello :)
Any plans re-releasing / open-sourcing the CMS 12 version?
It was available for a brief period on Nuget and now is gone :( 
https://www.nuget.org/packages/Epinova.ElasticSearch.Cms.Optimizely

**Comment by BorgKristian** [comment]
We have invested many hours of development time to upgrade the module to CMS 12. This has been an expense we have incurred internally. Therefore, we have chosen not to release it as open source. Please contact me if you would like more information.
