### ISSUE TITLE
PDF ingest attachment

### ISSUE THREAD

**Issue by paalm** [Epinova/Epinova.Elasticsearch#15]
I have trouble getting attachment mapper to map pdfs. Is it anything we have to do initially to make the mapping for pdfs or should it be handled in the mapper-plugin?
It seems we got the whole pdf as attachment in base64 so the ingester works ok, but I dont get any mappings.
Do I need to specify a mapping that will reflect the contents and metadata of index files?
How can I do it?

**Comment by lonnkvist** [comment]
Hi, I've found a bug in the mapping of attachment data. Working on a fix now.

**Comment by paalm** [comment]
I have tested it. It didnt solve my problem. It doesnt do the correct mapping for "Attachment". 
I got this mapping for the "Attachment" property.
        "properties": {
          "Attachment": {
            "type": "text",
            "fields": {
              "content": {
                "type": "text",
                "store": true,
                "term_vector": "with_positions_offsets"
              }
            }
          }
How are your mapping?
