### ISSUE TITLE
Elastic Search 8 support, no 'ingest-attachment' plugin should be needed!?

### ISSUE THREAD

**Issue by jonascarlbaum** [Epinova/Epinova.Elasticsearch#174]
`Elastic Search 8.4` seems to have plugin [`ingest-attachment`](https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-attachment.html) integrated  now, so no need for plugin?

Still indexing job produces this error when trying out `Elastic Search 8.4`.

```
Plugin 'ingest-attachment' is missing, please install it.
```

I tested `Elastic Search 8.4` with the **Docker Compose** [from here](https://www.elastic.co/guide/en/enterprise-search/8.4/docker.html#docker-compose-example).

Doing a **Docker Compose** of **Elastic Search 7.x** _(with additional command for installing plugin)_ works great.

**Comment by otanum** [comment]
Not Elastic 8+ ready yet. We need to finish .net 6 version before Elastic 8.

**Comment by jonascarlbaum** [comment]
Ok. Will the Elastic 8 support then be added for CMS 11/.NET 4.8 too?

**Comment by otanum** [comment]
Yes @jonascarlbaum

**Comment by fbacker** [comment]
Any update on this?

**Comment by otanum** [comment]
No update yet. We are currently working on a version for cms 12.  Elastic 8 support is next.

**Comment by jonatanjii** [comment]
@otanum I see there is a pre-release for Elastic 8 support, when will there be a stable release that supports Elastic 8?

**Comment by otanum** [comment]
@jonascarlbaum I don't know. I have not been able to verify the changes completely yet.

**Comment by jonatanjii** [comment]
@otanum does this mean that current version of Epinova 11.8.27 supports Elasticsearch 8.3 and below or is there no Elasticsearch 8 support at all?

**Comment by otanum** [comment]
No Elasticsearch 8 support at all I think. Breaking change how documents are stored in Elastic 8.

The elastic 8 release branch should work, but I have not recently tested myself.

**Comment by otanum** [comment]
Merged Elastic8 changes to main
