### ISSUE TITLE
When indexing content in a content area, it seems to only gather content from the master language

### ISSUE THREAD

**Issue by AThraen** [Epinova/Epinova.Elasticsearch#198]
In a multi-language site (on CMS 11), where pages and blocks exist in multiple languages, I've configured it to include a ContentArea property on all pages which contains a lot of blocks with the actual text on the site.
It looks like it only takes the contents of these blocks from the master language version of them - and not the other language versions.

I'm guessing that this is because it's using ContentAreaItem.Get() to get the content for each element in a content area, and this in turns uses the ContentLoader to fetch the content. The content loader will default to the current context culture to figure out which language version to load if it's not specified - however since the indexing happens in a scheduled job, the context won't matter and it will resort to master language. But that's just a guess. If this is indeed the problem I would suggest an alternate approach where the proper language is resolved directly instead of relying on ContentAreaItem.Get().

**Comment by otanum** [comment]
Could you please verify package version 11.8.8-Release-198-contentarea-language-bug?

**Comment by AThraen** [comment]
I can verify that it now does seem to index the correct language content for blocks in content areas, however - there is a new problem. It indexes the HTML encoded content into the parent pages MainContent. Here is an example in Icelandic:
"MainContent": "&Aacute; &thorn;remur vefkynningum f&aelig;r&eth;u inns&yacute;n &iacute; n&yacute;justu uppf&aelig;rsluna &aacute; sk&yacute;&thorn;j&oacute;nustu "

**Comment by otanum** [comment]
My changes is only related to the handling of ContentArea. Are you sure that nothing in your code indexes the HTML content. If not, is it possible to give us a little bit more details?

**Comment by AThraen** [comment]
I see now that my comment above got correctly encoded by github :-) My point was that in the indexing of the blocks in the content area, I'm guessing there is a .ToWebString() or something that html encodes special characters - so they end up in the index as & .... ; instead of the UTF-8 character, making them impossible to search for.

**Comment by otanum** [comment]
Try 11.8.21-Release-198-contentarea-language-bug

**Comment by AThraen** [comment]
That seems to work, thanks!

**Comment by otanum** [comment]
11.8.26
