### ISSUE TITLE
Bad request: no handler found for uri, Elasticsearch 8 version

### ISSUE THREAD

**Issue by jonatanjii** [Epinova/Epinova.Elasticsearch#208]
Hi,

Epinova.Elasticsearch: 11.8.41
Elasticsearch: 8.33

I get "no handler found for uri, bad request" in the following places after the upgrade:

Saving/creating a page in edit mode:
no handler found for uri [/alloy-dev%C2%A4en/Epinova_ElasticSearch_Core_Models_IndexItem/7] and method [PUT]"}.
 Status: 400 BadRequest

Creating/updating/deleting best bets (the part when the content item is updated, the best bet itself is saved in blob):
no handler found for uri [/alloy-dev%C2%A4en/Epinova_ElasticSearch_Core_Models_IndexItem/9/_update] and method [POST]

The scheduled job works
Searching works

Maybe this is related:
https://stackoverflow.com/questions/71477876/no-handler-found-for-uri-elasticsearch

/Jonatan

**Comment by otanum** [comment]
I'll try to take a look this week. The change from SO should have been implemented.

**Comment by jonatanjii** [comment]
Any update?

**Comment by otanum** [comment]
I am sorry. I got another big task that is urgent. Maybe next week.

**Comment by 1ewap** [comment]
Hello,

I've faced similar issue. It seems related to this change - https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html

This will fail -
PUT [index name]/Epinova_ElasticSearch_Core_Models_IndexItem/123

While this statement will succeed with a 201 status code in Kibana:
PUT [index name]/_doc/123

Can you please fix this soon? It complicates overall publishing functionality after Epinova and Elastic upgrade. We're using now Epinova 11.8.27 and Elastic 8.11.3

Regards,

**Comment by otanum** [comment]
Please verify release 11.8.59

**Comment by 1ewap** [comment]
Solved, thanks!
