### ISSUE TITLE
Search plugin sub-navigation disappeared with Episerver.CMS.UI v11.21 upgrade

### ISSUE THREAD

**Issue by jocuffey** [Epinova/Epinova.Elasticsearch#71]
Since the latest upgrade refreshing the CMS UI appearance, the sub-navigation within the plugin interface is gone 
![image](https://user-images.githubusercontent.com/6660589/60442191-d187d900-9c18-11e9-8c1b-b9f611ff2dff.png)

**Comment by lonnkvist** [comment]
Sadly this affects everyone using Html.GlobalMenu() for rendering the navigation. Episerver has actually just   pulled this update due to this and other problems. They informed me of this when I filed the bug report, and the recommendation was to go back to the previous version for now.
