### ISSUE TITLE
Update GUI to be aligned with Episerver new GUI

### ISSUE THREAD

**Issue by paalm** [Epinova/Epinova.Elasticsearch#73]
There is need to Update GUI to be aligned with Episerver new GUI.
Episerver has "refreshed" the GUI. The new UI comes with Episerver.CMS.UI 11.21.2.
This should maybe be optional if possible to make it compatible with the previous GUI of Episerver.

**Comment by lonnkvist** [comment]
Hi, support for this was added in 11.7.0.6. It works by checking if the new method `CreatePlatformNavigationMenu` exists or not.

![image](https://user-images.githubusercontent.com/220122/62685778-9a4cda80-b9c3-11e9-9caf-3688127d741e.png)
