### ISSUE TITLE
CoreIndexer inaccessible

### ISSUE THREAD

**Issue by paalm** [Epinova/Epinova.Elasticsearch#82]
To create custom types I do as mentioned in readme. This code gives me compile error on "CoreIndexer" because its an internal class:

`ICoreIndexer indexer = new Epinova.ElasticSearch.Core.CoreIndexer(settings);`

Should CoreIndexer be made public maybe?

**Comment by apeneve** [comment]
I think it is hidden for a good reason. Can you use  IoC or a service locator to fetch an instance of `ICoreIndexer` directly while waiting for the documentation update?
